---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[chef-client::config]
      - recipe[httpd::default]
      - recipe[httpd::ohai_plugin]
    attributes:
